version: "3"

services:
    db:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: Sora0218
            POSTGRES_USER: sorachi
            TZ: "Asia/Tokyo"
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    back:
        container_name: django
        build: ./dockerfiles/django_docker
        command: uwsgi --socket :8000 --http :8001  --module config.wsgi --py-autoreload 1 -b 32768
        volumes:
            - ./django:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

    front:
        container_name: nuxt
        build: ./dockerfiles/nuxt_docker
        tty: true
        command: >
            bash -c 'cd front && yarn dev'
        volumes:
            - ./nuxt:/code
        ports:
            - "3000:3000"

    nginx:
        image: nginx:1.13
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        depends_on:
            - back

volumes:
    pgdata:
