# Generated by Django 2.2.24 on 2021-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='work_thumbnail')),
                ('tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('repo_url', models.URLField(blank=True)),
                ('site_url', models.URLField(blank=True)),
            ],
        ),
    ]
